/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Course = IDL.Record({
  'professor' : IDL.Text,
  'creditHours' : IDL.Nat,
  'description' : IDL.Text,
  'courseCode' : IDL.Text,
  'courseName' : IDL.Text,
  'courseId' : IDL.Text,
});
export const StudentStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Time = IDL.Int;
export const StudentProfile = IDL.Record({
  'status' : StudentStatus,
  'studentId' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'fullName' : IDL.Text,
  'gradeLevel' : IDL.Nat,
  'enrollmentDate' : Time,
});
export const Enrollment = IDL.Record({
  'enrollmentId' : IDL.Text,
  'studentId' : IDL.Text,
  'grade' : IDL.Opt(IDL.Text),
  'enrollmentDate' : Time,
  'courseId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCourse' : IDL.Func([Course], [], []),
  'createStudent' : IDL.Func([StudentProfile], [], []),
  'deleteCourse' : IDL.Func([IDL.Text], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'enrollStudent' : IDL.Func([Enrollment], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
  'getEnrollmentsByCourse' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'getEnrollmentsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(StudentProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeEnrollment' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCourse' : IDL.Func([Course], [], []),
  'updateGrade' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateStudent' : IDL.Func([StudentProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Course = IDL.Record({
    'professor' : IDL.Text,
    'creditHours' : IDL.Nat,
    'description' : IDL.Text,
    'courseCode' : IDL.Text,
    'courseName' : IDL.Text,
    'courseId' : IDL.Text,
  });
  const StudentStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Time = IDL.Int;
  const StudentProfile = IDL.Record({
    'status' : StudentStatus,
    'studentId' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'fullName' : IDL.Text,
    'gradeLevel' : IDL.Nat,
    'enrollmentDate' : Time,
  });
  const Enrollment = IDL.Record({
    'enrollmentId' : IDL.Text,
    'studentId' : IDL.Text,
    'grade' : IDL.Opt(IDL.Text),
    'enrollmentDate' : Time,
    'courseId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCourse' : IDL.Func([Course], [], []),
    'createStudent' : IDL.Func([StudentProfile], [], []),
    'deleteCourse' : IDL.Func([IDL.Text], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'enrollStudent' : IDL.Func([Enrollment], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
    'getEnrollmentsByCourse' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'getEnrollmentsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(StudentProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeEnrollment' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCourse' : IDL.Func([Course], [], []),
    'updateGrade' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateStudent' : IDL.Func([StudentProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };