/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'professor' : string,
  'creditHours' : bigint,
  'description' : string,
  'courseCode' : string,
  'courseName' : string,
  'courseId' : string,
}
export interface Enrollment {
  'enrollmentId' : string,
  'studentId' : string,
  'grade' : [] | [string],
  'enrollmentDate' : Time,
  'courseId' : string,
}
export interface StudentProfile {
  'status' : StudentStatus,
  'studentId' : string,
  'dateOfBirth' : string,
  'fullName' : string,
  'gradeLevel' : bigint,
  'enrollmentDate' : Time,
}
export type StudentStatus = { 'active' : null } |
  { 'inactive' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<[Course], undefined>,
  'createStudent' : ActorMethod<[StudentProfile], undefined>,
  'deleteCourse' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'enrollStudent' : ActorMethod<[Enrollment], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllStudents' : ActorMethod<[], Array<StudentProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[string], [] | [Course]>,
  'getEnrollmentsByCourse' : ActorMethod<[string], Array<Enrollment>>,
  'getEnrollmentsByStudent' : ActorMethod<[string], Array<Enrollment>>,
  'getStudent' : ActorMethod<[string], [] | [StudentProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeEnrollment' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCourse' : ActorMethod<[Course], undefined>,
  'updateGrade' : ActorMethod<[string, string], undefined>,
  'updateStudent' : ActorMethod<[StudentProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];